### ISSUE TITLE
Не работает `web` контейнер.

### ISSUE THREAD

**Issue by NiKuma0** [Studio-Yandex-Practicum/sobitie#216]
# Why? 

При попытке зайти в админку или отправить API запрос, падает с ошибкой `Server Error (500)`.

# How To Do?

Проверить, работает ли админка локально. Если да, запустить в контейнерах.

**Comment by last-ui** [comment]
Контейнеры локально вроде работают.
Судя по логам worklow Deploy to server не отрабатываются команды:
            sudo docker-compose exec web python drf_sobitie/manage.py migrate
            sudo docker-compose exec web python drf_sobitie/manage.py collectstatic --no-input
Ошибка в логах worklow Deploy to server:
153 err: the input device is not a TTY
154 err: the input device is not a TTY
Можно попробовать добавить параметр -it:
sudo docker-compose exec -it web ...
