### ISSUE TITLE
BUG-14 [Раздел Как помочь][Кнопка Стать активным подписчиком][Несоответствие текста и кнопок]

### ISSUE THREAD

**Issue by Vikilapina** [Studio-Yandex-Practicum/sobitie#236]
Описание: Несоответствие текста и кнопок в разделе Стать активным подписчиком
Шаги:
1. Перейти в Telegram бот по ссылке
2. Кликнуть "/Start"
3. Кликнуть "Как помочь"
4. Кликнуть "Стать активным подписчиком"
ОР : Появляется текст с ссылками: "Социальные сети:[ВКонтакте](https://vk.com/sobytie.center)[Telegram](https://t.me/sobytiecenter)" и кнопка Назад
ФР: Появляется текст: "Спасибо большое за вашу поддержку! Вместе мы можем изменить мир к лучшему. 
Будем держать вас в курсе наших проектов и достижений в соцсетях." и кнопки Вконтакте,  Telegram, Назад
<img width="514" alt="ФР" src="https://github.com/Studio-Yandex-Practicum/sobitie/assets/146366019/fa7247d6-0889-4365-a91a-d6a47d5c3e5a">

Окружение:
iPhone 11 Pro 17.1.1 экран 5,8 2436x1125
MacOS Ventura 13.1 Яндекс Браузер 23.9.0.2325

**Comment by babyshitt** [comment]
#239 Исправлено
